// Validates zones-config.json without rendering anything.
// Checks zone geometry and how much of the safe zone survives once the
// player crops the canvas horizontally on tall screens.
// Run: node validate-zones.js

const fs = require('fs');
const path = require('path');

const config = JSON.parse(fs.readFileSync(path.join(__dirname, 'zones-config.json'), 'utf8'));
const { w: canvasW, h: canvasH, cropSafetyPx } = config.canvas;
const zones = config.overlay.safeZones;

// Players cover-fit the canvas, so a screen narrower than 9:16 loses the sides.
function cropPerSide(screenAR) {
  return Math.max(0, (canvasW - canvasH * screenAR) / 2);
}

// Reference devices: the two measured from real screenshots, plus the worst
// realistic full-bleed phone (20:9).
const DEVICES = [
  { name: 'iPhone full-bleed (measured)', ar: 923 / 1800 },
  { name: 'Android Reels (measured)', ar: 574 / 1077 },
  { name: '20:9 full-bleed (worst case)', ar: 9 / 20 },
];

let errors = 0;

for (const z of zones) {
  if (z.x < 0 || z.y < 0 || z.x + z.w > canvasW || z.y + z.h > canvasH) {
    console.log(`ERROR  zone out of canvas: ${JSON.stringify(z)}`);
    errors++;
  }
  if (z.w <= 0 || z.h <= 0) {
    console.log(`ERROR  non-positive zone size: ${JSON.stringify(z)}`);
    errors++;
  }
}

// Stacked zones must tile without gaps or overlaps and share an x, or the
// outline generated by generate-overlays.js will not close cleanly.
const sorted = [...zones].sort((a, b) => a.y - b.y);
for (let i = 0; i < sorted.length - 1; i++) {
  const gap = sorted[i + 1].y - (sorted[i].y + sorted[i].h);
  if (gap !== 0) {
    console.log(`ERROR  zones must be flush: ${gap > 0 ? 'gap' : 'overlap'} of ${Math.abs(gap)}px at y=${sorted[i].y + sorted[i].h}`);
    errors++;
  }
  if (sorted[i].x !== sorted[i + 1].x) {
    console.log(`ERROR  stacked zones must share the same x (${sorted[i].x} vs ${sorted[i + 1].x})`);
    errors++;
  }
}

const minLeft = Math.min(...zones.map((z) => z.x));
if (minLeft < cropSafetyPx) {
  console.log(`ERROR  left margin ${minLeft}px < crop safety ${cropSafetyPx}px`);
  errors++;
}

console.log(`${config.overlay.label} (${config.overlay.filename})`);
for (const z of zones) {
  console.log(`  zone y=${z.y}..${z.y + z.h}  x=${z.x}..${z.x + z.w}  ` +
    `(margins L${z.x} R${canvasW - (z.x + z.w)})`);
}
for (const d of DEVICES) {
  const crop = cropPerSide(d.ar);
  const worstRight = Math.min(...zones.map((z) => canvasW - crop - (z.x + z.w)));
  const left = minLeft - crop;
  const flag = left < 0 || worstRight < 0 ? '  <-- CLIPPED' : '';
  console.log(`  ${d.name}: crop ${crop.toFixed(0)}px/side -> ` +
    `visible margin L${left.toFixed(0)} R${worstRight.toFixed(0)}${flag}`);
  if (left < 0 || worstRight < 0) errors++;
}

console.log(`\n${errors} error(s).`);
if (errors > 0) process.exitCode = 1;
